### ISSUE TITLE
New eventsourcing version

### ISSUE THREAD

**Issue by johnbywater** [ApplauseOSS/djangoevents#24]
Hi guys,

I released a new major version of the eventsourcing library. https://pypi.python.org/pypi/eventsourcing/2.1.1

It's not backwards-compatible with the 1.x.x, there are some significant changes. If you wanted to update djangoevents to use the new version, you would need to make a few changes. Would be very happy to help you work through them, if you wanted some help with it.

Hope all's well,

John

**Comment by renou** [comment]
👍 congrats! thanks for letting us know!
