### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by M0dM** [ApplauseOSS/djangoevents#46]
Hi,

I am very interested in doing event sourcing with django.
It is not easy to understand how to use this library in a new or existing django project. 
Also, how easy is it to use it with other django apps in parallel ?

Could you please provide an example project using this module in parallel with django.contrib.auth ?

Does an open source project on github or elsewhere using this module exist that we could refer to ?

Many thanks.
M0dM

**Comment by Eimis** [comment]
Since https://github.com/ApplauseOSS/djangoevents/issues/24 hasn't been solved, I would assume active development for this project is stopped, right ?

**Comment by M0dM** [comment]
Thanks @Eimis
